#!/usr/bin/env python3
"""
Copy key metrics, deduped sweep, figure, and checkpoint pointers into ``results/submission/``.

Safe to re-run; overwrites bundle files (not your original sweep CSV).
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.report.robustness_figure import (  # noqa: E402
    dedupe_first,
    load_sweep_csv,
    short_label,
    write_sweep_csv,
)


def main() -> int:
    p = argparse.ArgumentParser(description="Collect submission artifacts under results/submission/")
    p.add_argument("--root", type=Path, default=_PROJECT_ROOT)
    args = p.parse_args()
    root = args.root.resolve()
    sub = root / "results" / "submission"
    sub.mkdir(parents=True, exist_ok=True)

    baseline = root / "results" / "speaker_baseline"
    sweep_src = baseline / "robustness_sweep.csv"
    if sweep_src.is_file():
        rows = dedupe_first(load_sweep_csv(sweep_src))
        write_sweep_csv(sub / "robustness_sweep_deduped.csv", rows)

    for name in ("eval_test_metrics.json", "robustness_metrics.json"):
        src = baseline / name
        if src.is_file():
            shutil.copy2(src, sub / name)

    fig = root / "results" / "figures" / "robustness_bars.png"
    if fig.is_file():
        shutil.copy2(fig, sub / "robustness_bars.png")

    # LaTeX table snippet (needs \usepackage{{booktabs}} in paper preamble)
    deduped_path = sub / "robustness_sweep_deduped.csv"
    tex_lines = []
    if deduped_path.is_file():
        with open(deduped_path, newline="", encoding="utf-8") as f:
            rdr = csv.DictReader(f)
            tex_lines.append(r"% Generated snippet — requires \usepackage{booktabs}")
            tex_lines.append(r"\begin{tabular}{lr}")
            tex_lines.append(r"\toprule")
            tex_lines.append(r"Condition & Accuracy \\")
            tex_lines.append(r"\midrule")
            for r in rdr:
                cond = short_label(r["attack"], r["params"])
                cond_tex = cond.replace("&", r"\&").replace("%", r"\%")
                tex_lines.append(f"{cond_tex} & {float(r['accuracy']):.4f} \\\\")
            tex_lines.append(r"\bottomrule")
            tex_lines.append(r"\end{tabular}")
        (sub / "table_robustness_snippet.tex").write_text("\n".join(tex_lines) + "\n", encoding="utf-8")

    meta = {
        "project_root": str(root),
        "checkpoint_relative": "results/speaker_baseline/speaker_cnn.pt",
        "label_map_relative": "results/speaker_baseline/speaker_label_map.json",
        "note": "Checkpoint and label map are large / binary-adjacent; kept in speaker_baseline/.",
    }
    (sub / "bundle_manifest.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    readme = sub / "README.md"
    readme.write_text(
        dedent(
            f"""
            # Submission bundle (generated)

            - `eval_test_metrics.json` — closed-set test BA (no attack).
            - `robustness_sweep_deduped.csv` — one row per attack setting (deduped).
            - `robustness_bars.png` — figure (run `scripts/07_plot_robustness_sweep.py` first).
            - `table_robustness_snippet.tex` — optional paste into ACM paper.
            - `table_robustness.md` — Markdown table (generated by `10_export_markdown_table.py`, also run from `08`).
            - `bundle_manifest.json` — paths to checkpoint files.

            ## Reproduce

            ```bash
            cd "{root}"
            source .venv/bin/activate
            export PYTHONPATH="$PWD"
            python scripts/10_reproduce_artifacts.py
            ```

            Or full pipeline: `04` → `06` → `07` → `08` → `09` (see main `README.md`).
            """
        ).lstrip(),
        encoding="utf-8",
    )

    env = {**os.environ, "PYTHONPATH": str(root)}
    md_script = root / "scripts" / "10_export_markdown_table.py"
    if md_script.is_file():
        r = subprocess.run([sys.executable, str(md_script)], cwd=str(root), env=env)
        if r.returncode != 0:
            return r.returncode

    print(f"Wrote bundle under {sub}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
